### ISSUE TITLE
Create a AWS account

### ISSUE THREAD

**Issue by giorgiosironi** [microsimulation/ijm#1]
From https://github.com/elifesciences/issues/issues/4837

This account needs to contain at least a bucket for Exeter to deliver articles in some format.

It looks like these articles would be used by a demo using Continuum rather than Libero, so unclear if anything else should live in there or if we should reuse the eLife infrastructure for Continuum.

**Comment by gnott** [comment]
The new account seemed appropriate for where the typesetter would deliver article content which I think is the most immediate requirement. 

I have no particular suggestion about other parts of the demo site, those can probably fit in anywhere for a short time.

**Comment by gnott** [comment]
For purposes of the demo site, a separate AWS account will not be required. We can download content from the typesetter's FTP site and then place it into eLife buckets and repos as required. Just wanted to let you know @giorgiosironi it is not a critical task to create a new account right now, I think.

**Comment by giorgiosironi** [comment]
> For purposes of the demo site, a separate AWS account will not be required

Agree, will just use the Libero one on a separate server from `unstable`.
