### ISSUE TITLE
Appendix content missing for 00185

### ISSUE THREAD

**Issue by FAtherden-eLife** [microsimulation/ijm#105]
The following from IJM was forwarded to me by Exeter:

> We noticed that appendix for the article https://microsimulation.pub/articles/00185 is not displayed on the website. Could you please check if the xml file you have provided contains the appendix?

Looks like there are some lists missing from [the appendix](https://microsimulation.pub/articles/00185#app1).

The content appears to be missing from the JSON:
https://github.com/microsimulation/ijm/blob/5edeadc999ee3e5df44aad6053057af390e63c6d/api/data/articles/00185.json#L1183-L1194

It looks to be there in the XML:
```xml
<app-group>
<app id="app1">
<title>Appendix</title>
<p>List of indicators estimated by the toolkit:
<list list-type="simple">
<list-item><p>- Poverty and Inequality rates over time, baseline and simulation scenarios (Sheet distindic):
<list list-type="bullet">
<list-item><p>time = simulation period</p></list-item>
<list-item><p>FGT0_base = poverty rate for baseline</p></list-item>
<list-item><p>FGT0_example = poverty rate for non-base simulation</p></list-item>
<list-item><p>FGT1_base = poverty gap rate for baseline</p></list-item>
<list-item><p>FGT1_example = poverty gap rate for non-base simulation</p></list-item>
<list-item><p>Gini_base = Gini coefficient for baseline</p></list-item>
<list-item><p>Gini_example = Gini coefficient for non-base simulation</p></list-item>
</list></p></list-item>
...
```

@gnott, do you know why this might be? 

@BlueReZZ FYI.

**Comment by gnott** [comment]
The difference I see with eLife appendices is the parsing we support right now is where each appendix is wrapped with a `<sec>` tag, whereas in the IJM article `00185` example, it is a `<p>` tag. If it is possible to write these appendices with a more eLife-like format then it would probably show up more readily.

If the XML you have above it something that should be supported and you'd consider it a bug, I could continue to get to the bottom of it and potentially solve it for eLife and others using our tooling. If you could please confirm @FAtherden-eLife whether the above is something we should be able to convert, we can see if the bug can be fixed.

**Comment by FAtherden-eLife** [comment]
Thanks for clarifying @gnott. I'll ask Exeter to resupply using the first paragraph as a section title (since, now that you mention it, it seems more appropriate anyway).

**Comment by FAtherden-eLife** [comment]
@gnott, Exeter have resupplied the appendix now with a `<sec>` - https://ijm-exeter-content-bucket.s3.amazonaws.com/ijm-00185.zip.

When you have chance, could you regenerate the JSON please?

**Comment by gnott** [comment]
Updated JSON in PR https://github.com/microsimulation/ijm/pull/106   It looks to have worked, although when viewing it on the website, the indent for each level of list or nested list is not the same as it appears in the PDF. Over to you @FAtherden-eLife!

**Comment by FAtherden-eLife** [comment]
Thanks @gnott. 
>  ... although when viewing it on the website, the indent for each level of list or nested list is not the same as it appears in the PDF

From looking at the JSON, I expect the output is probably acceptable.

**Comment by BlueReZZ** [comment]
@erkannt and I will look at #106 later this afternoon

**Comment by erkannt** [comment]
PR was merged and successfully deployed.
