### ISSUE TITLE
Group issues on homepage by 3-year dropdown

### ISSUE THREAD

**Issue by astrajescu** [microsimulation/ijm#16]
On the right-side of the homepage, the list of issues should be grouped into 3-year series using an accordion/drop-down principle, in a chronologically descending order.

![Annotation 2020-07-07 122954](https://user-images.githubusercontent.com/62929761/86760280-c77b9000-c04d-11ea-9cfc-f902e597ea64.png)

**Comment by BlueReZZ** [comment]
`main.js` is generated in the pattern library so an un-minimised version is available there:

https://github.com/elifesciences/pattern-library/tree/develop/assets/js

You'll notice that it brings in other component JS files, and the one you are likely interested in for page section closing/opening is https://github.com/elifesciences/pattern-library/blob/develop/assets/js/components/ArticleSection.js

**Comment by magrigor** [comment]
Our dev team facing with a problem to create a new view-model/converter in ijm, which is required for that ticket, help was requested from Chris and Giorgio, moving ticket to blocked until receive more technical details on that.

**Comment by BlueReZZ** [comment]
@magrigor there is an update to the `category-group` branch that changes the `HomeController` to use a static constructor for the `CategoryGroup` wrapper, with a converter for the "Teasers" within it.

This renders the list as before but allows us to use a new mustache template for the wrapper - you just need to swap this line:
https://github.com/microsimulation/ijm/blob/3dc1ffb175e28189c26d3e0f986a6c7ed89fb00f/journal/src/Patterns/ViewModel/CategoryGroup.php#L60

to point at a new mustache template and it should work

Hope this unblocks the ticket enough.
