### ISSUE TITLE
Discard Editorial as a content category

### ISSUE THREAD

**Issue by astrajescu** [microsimulation/ijm#18]
Look into the existing content category Editorial (http://microsimulation.pub/articles/editorial) and remove from categorization since it is not a research oriented category.
Content of this type should not be indexed fur browsing/selecting purpose.

**Comment by hdrury1** [comment]
Going to close this issue following discussion. While we won't include 'Editorial' as a navigation option in the course of implementing #17 we shouldn't remove it as a content type from the codebase.
