### ISSUE TITLE
Convert all IJM XML content to JSON

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm#2]

**Comment by gnott** [comment]
I have started with the articles from volume 1, issue 1, committed first draft in branch https://github.com/microsimulation/demo/tree/volume1. Article 00005 is still not valid due to a conference reference requiring an XML fix before the reference can be valid.

**Comment by gnott** [comment]
I am adding all content up to article `00054` today, in the form has been supplied so far. I suspect these will require resupplying, but it has allowed me to create issues as collections for these.

**Comment by gnott** [comment]
As of today, each article is available on the demo journal site, the latest content available.

**Comment by thewilkybarkid** [comment]
Great effort, thanks!
