### ISSUE TITLE
Feature test failing due to different header structure on article

### ISSUE THREAD

**Issue by erkannt** [microsimulation/ijm#204]
CI is failing due to a failing feature test:

![image](https://github.com/microsimulation/ijm/assets/19282025/5fd3cfb0-2a06-4e88-bd34-497dd901e1e0)

**Comment by erkannt** [comment]
A local run of `make test` is green.

**Comment by erkannt** [comment]
Looks like the issue is stemming from this article being the first on the homepage right now. It has less content in the header than usual. The selector in the cucumber tests relied on an exact amount of `divs`.

![image](https://github.com/microsimulation/ijm/assets/19282025/79f30d3f-f3e3-4c66-97f0-e1e53a1ef701)

**Comment by pbronka** [comment]
Thank you very much @erkannt . I didn't want to break anything further with the pipeline but I've looked at the change you made and think understood better how the tests are implemented -  so if any fails in the future, I will give fixing it a go.

**Comment by erkannt** [comment]
No worries. If you haven't yet give the `Makefile` a look. You can run the server and tests locally using `make dev` and `make test` respectively. There is some documentation for this in the readme.
