### ISSUE TITLE
(Bug) Article 00089 fails to load with http500

### ISSUE THREAD

**Issue by astrajescu** [microsimulation/ijm#22]
An article page fails with error - "Value "" is blank, but was expected to contain a value.
Link to the article: http://microsimulation.pub/articles/00089

![Annotation 2020-07-27 151029](https://user-images.githubusercontent.com/62929761/88540302-5bbc8f80-d01b-11ea-80f7-07e712b6cc18.png)

**Comment by astrajescu** [comment]
The article title is "The COMPARE Microsimulation Model and the U.S. Affordable Care Act" from Volume 6(3).

**Comment by astrajescu** [comment]
While investigating this issue, the developers found that there is section in JSON file 'acronyms' which, because it is null, is failing to load the entire article. After some experiments with this section (by the way it is the only file with such a section and maybe that's the reason of failing - maybe the conversion algorithm does not recognize such section) we've found that if we remove it from JSON file, the article will successfully load on the site, so for now we have implemented this as a solution to show the article. However we need Graham @gnott to come up with his vision of a permanent solution.

**Comment by gnott** [comment]
I think the ultimate cause of the error is this section in the JSON, where the content is blank:

```
    "appendices": [
        {
            "content": [],
            "id": "A1",
            "title": "Acronyms"
        }
    ],
```

It may be something @FAtherden-eLife would want to be included in, because the article XML itself may require changing for the appendix content to be extracted in the conversion process.

**Comment by FAtherden-eLife** [comment]
I have asked Exeter to redeliver this content captured in a separate way (as tables in an appendix), which should mean that we can render the content and avoid this error.
