### ISSUE TITLE
Ask Exeter to add most recent content to bucket

### ISSUE THREAD

**Issue by hdrury1** [microsimulation/ijm#26]
@FAtherden-eLife to contact Exeter and ask for latest content to be added to appropriate bucket.

**Comment by FAtherden-eLife** [comment]
Exeter said that they will deliver this content by the end of next week.

**Comment by FAtherden-eLife** [comment]
The latest IJM content is now in the Exeter FTP in the following folder - `/IJM/Articles/Latest IJM content`.

**Comment by FAtherden-eLife** [comment]
@gnott, FYI.
