### ISSUE TITLE
Commit latest IJM content to repo

### ISSUE THREAD

**Issue by hdrury1** [microsimulation/ijm#27]
Task for @gnott 

Figures and PDF to be added to assets folder

**Comment by gnott** [comment]
Plus if it's not covered in another ticket, generate JSON from the XML files and add new collection / issue data for the latest content.

**Comment by BlueReZZ** [comment]
FYI @astrajescu the original XML files for the latest issues are available here: https://exeterpremedia.exavault.com/share/view/22wu5-5uqj0bpu

I am arranging for Exeter to deliver all the content to a bucket on the `IJM` AWS account so that we have everything in one place
