### ISSUE TITLE
Demo site assertion

### ISSUE THREAD

**Issue by gnott** [microsimulation/ijm#4]
**Describe the bug**
Visiting http://localhost:8080/ or http://localhost:8080/collections raises `Media type 'application/json' is missing a version parameter` exception in the https://github.com/microsimulation/demo project.

**Steps To Reproduce**
```
git checkout example
docker-compose up
curl http://localhost:8080
```

There is detail about the exception in the docker log.

**Expected behavior**
No exception, with some content displayed? (I guess). I had this exception last week too but I thought perhaps the lack of content was causing the exception.

**Screenshots**

Most applicable log entry:

```
journal_1  | [26-Apr-2019 18:29:58] WARNING: [pool www] child 7 said into stderr: "[2019-04-26 18:29:58] request.CRITICAL: Uncaught PHP Exception eLife\ApiClient\Exception\ApiException: "Media type 'application/json' is missing a version parameter" at /app/vendor/elife/api-client/src/HttpClient/Guzzle6HttpClient.php line 65 {"exception":"[object] (eLife\\ApiClient\\Exception\\ApiException(code: 0): Media type 'application/json' is missing a version parameter at /app/vendor/elife/api-client/src/HttpClient/Guzzle6HttpClient.php:65, UnexpectedValueException(code: 0): Media type 'application/json' is missing a version parameter at /app/vendor/elife/api-client/src/Result/HttpResult.php:30, Assert\\InvalidArgumentException(code: 26): Media type 'application/json' is missing a version parameter at /app/vendor/beberlei/assert/lib/Assert/Assertion.php:288)"} []"
```

Lovely screen shot, which is probably not as useful as the log entry

![image](https://user-images.githubusercontent.com/1779115/56828894-2b35e680-6817-11e9-9cd5-21c864a99919.png)

I vaguely looked around to see if I could track down something I did wrong, but it is beyond my knowledge. If you have some ideas please @thewilkybarkid that would be super - thanks!

**Comment by giorgiosironi** [comment]
Same error for me:
```
Media type 'application/json' is missing a version parameter
```
Also http://localhost:8080/ping and http://localhost:8080/status answer with `404 Not Found`.

**Comment by thewilkybarkid** [comment]
Fixed by https://github.com/microsimulation/demo/commit/c57886f9d042bd61981299d75adea61fd414a43e.

**Comment by gnott** [comment]
Thanks @thewilkybarkid! I think that will do it.
