### ISSUE TITLE
Remove section headings in some articles

### ISSUE THREAD

**Issue by astrajescu** [microsimulation/ijm#45]
Exeter related task. @FAtherden-eLife and @gnott - FYI.

Editorials, Research notes, Software reviews and Book Reviews have no sections so we need to remove the words "Main text" which look like a section heading. See the PDF version.

**Comment by FAtherden-eLife** [comment]
This isn't an Exeter task. It looks like the bot adds a section with the title 'Main text' to the generated JSON, if there isn't one in the XML - [example](https://github.com/microsimulation/demo/blob/7403d26b62d5e575829e8c6de20850ea95b7d485/api/data/articles/00162.json#L86-L88).

Presume an overall section for the text is mandated in the RAML Schema or for something else.

**Comment by hdrury1** [comment]
This is part of a wider issue of how we deal with any article that has no section headings. The bot rules need updating.
