### ISSUE TITLE
Remove words "Review of" from Book reviews titles

### ISSUE THREAD

**Issue by astrajescu** [microsimulation/ijm#46]
Exeter related task. @FAtherden-eLife and @gnott - FYI.

Remove words "Review of" from titles of Book reviews. However, clarification is needed as the PDF version contains it and we aim to have consistency between the two.

**Comment by FAtherden-eLife** [comment]
Exeter have redelivered this content (presumably on the request of Matteo). It available on their FTP in `IJM/Book review articles`.

**Comment by gnott** [comment]
This article still has "Review of" http://microsimulation.pub/articles/00204, others are all resupplied now

**Comment by FAtherden-eLife** [comment]
Hmm, I don't know if this is deliberate or not though. @BlueReZZ, could you check with Matteo, and then we can ask Exeter to resupply if necessary?

**Comment by BlueReZZ** [comment]
Thanks @FAtherden-eLife I've emailed IJM and cc'd you as this does indeed look like an oversight at Exeter

**Comment by BlueReZZ** [comment]
From Patryk at IJM: 
> this article has now been updated by Exeter and they reuploaded the XML (here: https://exeterpremedia.exavault.com/share/view/22wu5-5uqj0bpu).

**Comment by gnott** [comment]
If there are no objections from anyone watching this issue, I will download all those articles, convert them to JSON and assets and put into a PR.

**Comment by BlueReZZ** [comment]
@FAtherden-eLife  suggested that the ones we were waiting for in #70 for their dates to be corrected have now been fixed so I think converting those ones at that link seems to be a good step forward, no objections here.
