### ISSUE TITLE
Final journal website tweaks for demonstration

### ISSUE THREAD

**Issue by BlueReZZ** [microsimulation/ijm#6]
## Problem / Motivation
A few minor tweaks to the demo site to make it look more realistic before the demonstration to IJM's congress and board on June 17th - 19th June

## Proposed solution
Add in the following: 
- [x] A header image, see attachment
- [x] A link for submission of new research, pointing to https://www.epress.ac.uk//ijm/webforms/author.php
- [x] The following web pages, with appropriate links from the web page:
    - [x] Aims and scope (same content as in https://microsimulation.org/ijm/)
    - [x] Editorial board (same content as in https://microsimulation.org/ijm/editorial-board/)
    - [x] Submission policy (same content as in https://microsimulation.org/ijm/submission-policy/)
    - [x] Note for authors (same content as in https://microsimulation.org/ijm/notes-for-authors/, but only up until how to submit (excluded). Last sentence: “For questions, please contact the Editor Matteo Richiardi at matteo.richiardi@essex.ac.uk”.
     - [x] Note for reviewers (same content as in https://microsimulation.org/ijm/notes-for-reviewers/)
- [x] Make DOIs not clickable

## Technical Solution
All of the code for the IJM demo is in the https://github.com/microsimulation/demo repo which consists of a copy of patterns, journal, an image server and dummy API
These changes are likely to be made to patterns or journal only.

## User interface / Wireframes
Header image to use
![IJM cover](https://user-images.githubusercontent.com/578113/59105587-28590600-892c-11e9-9d02-611ca3f203f4.jpg)

**Comment by discodavey** [comment]
I have done all of the work apart from the image which Chris will take a look at as it's not showing even though all the others are in the same folder. Will let you know when this is done.

https://github.com/microsimulation/demo/pull/23

**Comment by thewilkybarkid** [comment]
Deployed, good to close? /cc @Melissa37

**Comment by Melissa37** [comment]
I'd say so! Thanks. I've not QC'd I'll leave that to Matteo

**Comment by BlueReZZ** [comment]
Matteo responded with:
> That looks awesome! 

So I'll close this on that basis. We won't have time to change much before he needs to show it now anyway so we'll have to treat any new issues as new issues.
