### ISSUE TITLE
Figures are not displaying

### ISSUE THREAD

**Issue by hdrury1** [microsimulation/ijm#7]
<img width="1280" alt="Screenshot 2020-07-02 at 11 25 53" src="https://user-images.githubusercontent.com/17023702/86348016-0331e680-bc57-11ea-95b9-e24dbcba6815.png">

Figures not displaying within the article, and unable to load when linking out.

**Comment by rtudvasev** [comment]
Fixed by setting lower DNS cache TTL and correct environment variables
