### ISSUE TITLE
Rewrite rules for Nginx

### ISSUE THREAD

**Issue by astrajescu** [microsimulation/ijm#76]
Mask/hide the nginx and PHP versions of site from response headers.

CWE-200 -
risk: low
tech details: server leaks technology stack info in response headers:

Server: nginx/1.15.5
X-Powered-By: PHP/7.0.29

vulnerability: Access to such information may facilitate attackers identifying other frameworks/components your web application is reliant upon and the vulnerabilities such components may be subject to.

**Comment by rtudvasev** [comment]
Added in https://github.com/microsimulation/ijm/commit/ffb2ff3fc58ae59cd4617ac8653abbf30f5759d0
