### ISSUE TITLE
AWS Bucket for Exeter to upload all the updated content

### ISSUE THREAD

**Issue by astrajescu** [microsimulation/ijm#84]
Create an AWS bucket repo where Exeter would upload all the updated content for IJM site.

**Comment by rtudvasev** [comment]
Created S3 bucket with name **ijm-exeter-content-bucket** and a user with access specific to this bucket only[programmatic access only].

I`d like to suggest S3 Browser as S3 GUI client if it`s required

**Comment by rtudvasev** [comment]
Credentials and bucket name have been shared  with Fred, so he could send them to Exeter
