### ISSUE TITLE
(Bug) Articles #151 and 185 are incorrectly tagged

### ISSUE THREAD

**Issue by astrajescu** [microsimulation/ijm#91]
These two articles are 'Software reviews', but they are tagged as 'Book reviews' instead. In the xml file they are tagged correctly but it seems that in the conversion process they are categorized as 'Book reviews' (Scientific-correspondence).

**Comment by gnott** [comment]
The values were the result of replacements in the generation library I'm running, lines https://github.com/elifesciences/bot-lax-adaptor/blob/ijm/src/main.py#L76 or https://github.com/elifesciences/bot-lax-adaptor/blob/ijm/src/main.py#L101 would convert the XML value to `scientific-correspondence` in the JSON output.

I'm changing the code to generate `registered-report` instead so we won't get caught by this again, if we convert these again.
